---
- hosts: '{{ hosts }}'
  tasks:
  - name: copy the zip to target
    copy: src=imseam-framework-test.zip dest={{target_location}}
  - name: unzip the file
    shell: unzip imseam-framework-test.zip -d imseam
  - name: setup executable permission
    shell: chmod 740 imseam/bin/*.sh


