//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.31 at 10:52:09 PM MDT 
//


package com.imseam.chatlet.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chatlet-app-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chatlet-app-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="init-params" type="{http://www.imseam.com/}params" minOccurs="0"/>
 *         &lt;element name="connection-factoriess" type="{http://www.imseam.com/}connection-factories" minOccurs="0"/>
 *         &lt;element name="connections" type="{http://www.imseam.com/}connections" minOccurs="0"/>
 *         &lt;element name="listeners" type="{http://www.imseam.com/}listeners" minOccurs="0"/>
 *         &lt;element name="filter-mappings" type="{http://www.imseam.com/}filter-mappings" minOccurs="0"/>
 *         &lt;element name="chatlet" type="{http://www.imseam.com/}chatlet-config"/>
 *         &lt;element name="meeting-event-listener" type="{http://www.imseam.com/}meeting-event-listener-config"/>
 *       &lt;/sequence>
 *       &lt;attribute name="application-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chatlet-app-config", propOrder = {
    "initParams",
    "resourceBundle",
    "connectionFactoriess",
    "connections",
    "listeners",
    "filterMappings",
    "chatlet",
    "meetingEventListener"
})
public class ChatletAppConfig {

    @XmlElement(name = "init-params")
    protected Params initParams;
    @XmlElement(name = "resource-bundle")
    protected ResourceBundleConfig resourceBundle;
    @XmlElement(name = "connection-factoriess")
    protected ConnectionFactories connectionFactoriess;
    protected Connections connections;
    protected Listeners listeners;
    @XmlElement(name = "filter-mappings")
    protected FilterMappings filterMappings;
    public ResourceBundleConfig getResourceBundle() {
		return resourceBundle;
	}

	public void setResourceBundle(ResourceBundleConfig resourceBundle) {
		this.resourceBundle = resourceBundle;
	}

	@XmlElement(required = true)
    protected ChatletConfig chatlet;
    @XmlElement(name = "meeting-event-listener", required = true)
    protected MeetingEventListenerConfig meetingEventListener;
    @XmlAttribute(name = "application-name")
    protected String applicationName;

    /**
     * Gets the value of the initParams property.
     * 
     * @return
     *     possible object is
     *     {@link Params }
     *     
     */
    public Params getInitParams() {
        return initParams;
    }

    /**
     * Sets the value of the initParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Params }
     *     
     */
    public void setInitParams(Params value) {
        this.initParams = value;
    }

    /**
     * Gets the value of the connectionFactoriess property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionFactories }
     *     
     */
    public ConnectionFactories getConnectionFactoriess() {
        return connectionFactoriess;
    }

    /**
     * Sets the value of the connectionFactoriess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionFactories }
     *     
     */
    public void setConnectionFactoriess(ConnectionFactories value) {
        this.connectionFactoriess = value;
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link Connections }
     *     
     */
    public Connections getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connections }
     *     
     */
    public void setConnections(Connections value) {
        this.connections = value;
    }

    /**
     * Gets the value of the listeners property.
     * 
     * @return
     *     possible object is
     *     {@link Listeners }
     *     
     */
    public Listeners getListeners() {
        return listeners;
    }

    /**
     * Sets the value of the listeners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Listeners }
     *     
     */
    public void setListeners(Listeners value) {
        this.listeners = value;
    }

    /**
     * Gets the value of the filterMappings property.
     * 
     * @return
     *     possible object is
     *     {@link FilterMappings }
     *     
     */
    public FilterMappings getFilterMappings() {
        return filterMappings;
    }

    /**
     * Sets the value of the filterMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterMappings }
     *     
     */
    public void setFilterMappings(FilterMappings value) {
        this.filterMappings = value;
    }

    /**
     * Gets the value of the chatlet property.
     * 
     * @return
     *     possible object is
     *     {@link ChatletConfig }
     *     
     */
    public ChatletConfig getChatlet() {
        return chatlet;
    }

    /**
     * Sets the value of the chatlet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChatletConfig }
     *     
     */
    public void setChatlet(ChatletConfig value) {
        this.chatlet = value;
    }

    /**
     * Gets the value of the meetingEventListener property.
     * 
     * @return
     *     possible object is
     *     {@link MeetingEventListenerConfig }
     *     
     */
    public MeetingEventListenerConfig getMeetingEventListener() {
        return meetingEventListener;
    }

    /**
     * Sets the value of the meetingEventListener property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeetingEventListenerConfig }
     *     
     */
    public void setMeetingEventListener(MeetingEventListenerConfig value) {
        this.meetingEventListener = value;
    }

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationName(String value) {
        this.applicationName = value;
    }

}
