//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.31 at 10:52:09 PM MDT 
//


package com.imseam.chatlet.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for engine-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="engine-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connectors" type="{http://www.imseam.com/}connectors"/>
 *         &lt;element name="filters" type="{http://www.imseam.com/}filters" minOccurs="0"/>
 *         &lt;element name="chatlet-apps" type="{http://www.imseam.com/}chatlet-apps"/>
 *       &lt;/sequence>
 *       &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "engine-config", propOrder = {
    "connectors",
    "filters",
    "chatletApps"
})
public class EngineConfig {

    @XmlElement(required = true)
    protected Connectors connectors;
    protected Filters filters;
    @XmlElement(name = "chatlet-apps", required = true)
    protected ChatletApps chatletApps;
    @XmlAttribute(name = "class-name")
    protected String className;

    /**
     * Gets the value of the connectors property.
     * 
     * @return
     *     possible object is
     *     {@link Connectors }
     *     
     */
    public Connectors getConnectors() {
        return connectors;
    }

    /**
     * Sets the value of the connectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connectors }
     *     
     */
    public void setConnectors(Connectors value) {
        this.connectors = value;
    }

    /**
     * Gets the value of the filters property.
     * 
     * @return
     *     possible object is
     *     {@link Filters }
     *     
     */
    public Filters getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filters }
     *     
     */
    public void setFilters(Filters value) {
        this.filters = value;
    }

    /**
     * Gets the value of the chatletApps property.
     * 
     * @return
     *     possible object is
     *     {@link ChatletApps }
     *     
     */
    public ChatletApps getChatletApps() {
        return chatletApps;
    }

    /**
     * Sets the value of the chatletApps property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChatletApps }
     *     
     */
    public void setChatletApps(ChatletApps value) {
        this.chatletApps = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

}
