//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.31 at 10:52:09 PM MDT 
//


package com.imseam.chatlet.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for meeting-event-listener-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="meeting-event-listener-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="init-params" type="{http://www.imseam.com/}params" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="meeting-event-listener-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "meeting-event-listener-config", propOrder = {
    "initParams"
})
public class MeetingEventListenerConfig {

    @XmlElement(name = "init-params")
    protected Params initParams;
    @XmlAttribute(name = "meeting-event-listener-class", required = true)
    protected String meetingEventListenerClass;

    /**
     * Gets the value of the initParams property.
     * 
     * @return
     *     possible object is
     *     {@link Params }
     *     
     */
    public Params getInitParams() {
        return initParams;
    }

    /**
     * Sets the value of the initParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Params }
     *     
     */
    public void setInitParams(Params value) {
        this.initParams = value;
    }

    /**
     * Gets the value of the meetingEventListenerClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeetingEventListenerClass() {
        return meetingEventListenerClass;
    }

    /**
     * Sets the value of the meetingEventListenerClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeetingEventListenerClass(String value) {
        this.meetingEventListenerClass = value;
    }

}
