//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.31 at 10:52:09 PM MDT 
//


package com.imseam.chatlet.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.imseam.chatlet.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ChatletEngine_QNAME = new QName("http://www.imseam.com/", "chatlet-engine");
    private final static QName _ChatletApp_QNAME = new QName("http://www.imseam.com/", "chatlet-app");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.imseam.chatlet.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link FilterConfig }
     * 
     */
    public FilterConfig createFilterConfig() {
        return new FilterConfig();
    }

    /**
     * Create an instance of {@link Connections }
     * 
     */
    public Connections createConnections() {
        return new Connections();
    }

    /**
     * Create an instance of {@link AppContextConfig }
     * 
     */
    public AppContextConfig createAppContextConfig() {
        return new AppContextConfig();
    }

    /**
     * Create an instance of {@link ChatletConfig }
     * 
     */
    public ChatletConfig createChatletConfig() {
        return new ChatletConfig();
    }

    /**
     * Create an instance of {@link ListenerConfig }
     * 
     */
    public ListenerConfig createListenerConfig() {
        return new ListenerConfig();
    }

    /**
     * Create an instance of {@link ResourceBundleConfig }
     * 
     */
    public ResourceBundleConfig createResourceBundleConfig() {
        return new ResourceBundleConfig();
    }
    /**
     * Create an instance of {@link ChatletAppConfig }
     * 
     */
    public ChatletAppConfig createChatletAppConfig() {
        return new ChatletAppConfig();
    }

    /**
     * Create an instance of {@link MeetingEventListenerConfig }
     * 
     */
    public MeetingEventListenerConfig createMeetingEventListenerConfig() {
        return new MeetingEventListenerConfig();
    }

    /**
     * Create an instance of {@link EngineConfig }
     * 
     */
    public EngineConfig createEngineConfig() {
        return new EngineConfig();
    }

    /**
     * Create an instance of {@link ConnectionFactoryConfig }
     * 
     */
    public ConnectionFactoryConfig createConnectionFactoryConfig() {
        return new ConnectionFactoryConfig();
    }

    /**
     * Create an instance of {@link Filters }
     * 
     */
    public Filters createFilters() {
        return new Filters();
    }

    /**
     * Create an instance of {@link FilterMappings }
     * 
     */
    public FilterMappings createFilterMappings() {
        return new FilterMappings();
    }

    /**
     * Create an instance of {@link Listeners }
     * 
     */
    public Listeners createListeners() {
        return new Listeners();
    }

    /**
     * Create an instance of {@link ConnectionFactories }
     * 
     */
    public ConnectionFactories createConnectionFactories() {
        return new ConnectionFactories();
    }

    /**
     * Create an instance of {@link ChatletApps }
     * 
     */
    public ChatletApps createChatletApps() {
        return new ChatletApps();
    }

    /**
     * Create an instance of {@link Params }
     * 
     */
    public Params createParams() {
        return new Params();
    }

    /**
     * Create an instance of {@link ConnectionConfig }
     * 
     */
    public ConnectionConfig createConnectionConfig() {
        return new ConnectionConfig();
    }

    /**
     * Create an instance of {@link Connectors }
     * 
     */
    public Connectors createConnectors() {
        return new Connectors();
    }

    /**
     * Create an instance of {@link ConnectorConfig }
     * 
     */
    public ConnectorConfig createConnectorConfig() {
        return new ConnectorConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EngineConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imseam.com/", name = "chatlet-engine")
    public JAXBElement<EngineConfig> createChatletEngine(EngineConfig value) {
        return new JAXBElement<EngineConfig>(_ChatletEngine_QNAME, EngineConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChatletAppConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.imseam.com/", name = "chatlet-app")
    public JAXBElement<ChatletAppConfig> createChatletApp(ChatletAppConfig value) {
        return new JAXBElement<ChatletAppConfig>(_ChatletApp_QNAME, ChatletAppConfig.class, null, value);
    }

}
