//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.09 at 11:34:38 PM MDT 
//


package com.imseam.chatpage.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.imseam.com/}chat-page"/>
 *         &lt;element ref="{http://www.imseam.com/}menu-page"/>
 *         &lt;element name="global-parsers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;group ref="{http://www.imseam.com/}parser-elements"/>
 *                   &lt;element name="grouped-parser" type="{http://www.imseam.com/}grouped-parser"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.imseam.com/}command-filter"/>
 *         &lt;element name="command-filter-mapping" type="{http://www.imseam.com/}command-filter-mapping"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chatPageOrMenuPageOrGlobalParsers"
})
@XmlRootElement(name = "chat-pages")
public class ChatPagesInfo {

    @XmlElements({
        @XmlElement(name = "command-filter-mapping", type = CommandFilterMappingInfo.class),
        @XmlElement(name = "command-filter", type = CommandFilterInfo.class),
        @XmlElement(name = "global-parsers", type = ChatPagesInfo.GlobalParsersInfo.class),
        @XmlElement(name = "chat-page", type = ChatPageInfo.class),
        @XmlElement(name = "menu-page", type = MenuPageInfo.class)
    })
    protected List<Object> chatPageOrMenuPageOrGlobalParsers;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the chatPageOrMenuPageOrGlobalParsers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chatPageOrMenuPageOrGlobalParsers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChatPageOrMenuPageOrGlobalParsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandFilterMapping }
     * {@link CommandFilter }
     * {@link ChatPages.GlobalParsers }
     * {@link ChatPage }
     * {@link MenuPage }
     * 
     * 
     */
    public List<Object> getChatPageOrMenuPageOrGlobalParsers() {
        if (chatPageOrMenuPageOrGlobalParsers == null) {
            chatPageOrMenuPageOrGlobalParsers = new ArrayList<Object>();
        }
        return this.chatPageOrMenuPageOrGlobalParsers;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;group ref="{http://www.imseam.com/}parser-elements"/>
     *         &lt;element name="grouped-parser" type="{http://www.imseam.com/}grouped-parser"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "regexpParserOrJavaParserOrStringParser"
    })
    public static class GlobalParsersInfo {

        @XmlElements({
            @XmlElement(name = "parser-ref", type = ParserRefInfo.class),
            @XmlElement(name = "java-parser", type = JavaParserInfo.class),
            @XmlElement(name = "regexp-parser", type = RegexpParserInfo.class),
            @XmlElement(name = "string-parser", type = StringParserInfo.class),
            @XmlElement(name = "grouped-parser", type = GroupedParserInfo.class)
        })
        protected List<Object> regexpParserOrJavaParserOrStringParser;

        /**
         * Gets the value of the regexpParserOrJavaParserOrStringParser property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the regexpParserOrJavaParserOrStringParser property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRegexpParserOrJavaParserOrStringParser().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ParserRef }
         * {@link JavaParser }
         * {@link RegexpParser }
         * {@link StringParser }
         * {@link GroupedParser }
         * 
         * 
         */
        public List<Object> getRegexpParserOrJavaParserOrStringParser() {
            if (regexpParserOrJavaParserOrStringParser == null) {
                regexpParserOrJavaParserOrStringParser = new ArrayList<Object>();
            }
            return this.regexpParserOrJavaParserOrStringParser;
        }

    }

}
