//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.09 at 11:34:38 PM MDT 
//


package com.imseam.chatpage.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.imseam.com/}response" minOccurs="0"/>
 *         &lt;element name="menu-item" type="{http://www.imseam.com/}response"/>
 *         &lt;element name="footer" type="{http://www.imseam.com/}response" minOccurs="0"/>
 *         &lt;element name="help" type="{http://www.imseam.com/}response" minOccurs="0"/>
 *         &lt;element name="menu-selected-action" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actions" type="{http://www.imseam.com/}actions" minOccurs="0"/>
 *         &lt;element name="params" type="{http://www.imseam.com/}params" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="view-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="items" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="var" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="page-size" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "menuItem",
    "footer",
    "help",
    "menuSelectedAction",
    "actions",
    "params"
})
@XmlRootElement(name = "menu-page")
public class MenuPageInfo {

    protected ResponseInfo header;
    @XmlElement(name = "menu-item", required = true)
    protected ResponseInfo menuItem;
    protected ResponseInfo footer;
    protected ResponseInfo help;
    protected ActionsInfo actions;
    protected ParamsInfo params;
    @XmlAttribute(name = "view-id", required = true)
    protected String viewId;
    @XmlAttribute(required = true)
    protected String items;
    @XmlAttribute
    protected String var;
    @XmlAttribute(name = "page-size")
    protected String pageSize;
    @XmlAttribute(name = "menu-selected-action")
    protected String menuSelectedAction;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public ResponseInfo getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setHeader(ResponseInfo value) {
        this.header = value;
    }

    /**
     * Gets the value of the menuItem property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public ResponseInfo getMenuItem() {
        return menuItem;
    }

    /**
     * Sets the value of the menuItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setMenuItem(ResponseInfo value) {
        this.menuItem = value;
    }

    /**
     * Gets the value of the footer property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public ResponseInfo getFooter() {
        return footer;
    }

    /**
     * Sets the value of the footer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setFooter(ResponseInfo value) {
        this.footer = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public ResponseInfo getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setHelp(ResponseInfo value) {
        this.help = value;
    }

    /**
     * Gets the value of the menuSelectedAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuSelectedAction() {
        return menuSelectedAction;
    }

    /**
     * Sets the value of the menuSelectedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuSelectedAction(String value) {
        this.menuSelectedAction = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link Actions }
     *     
     */
    public ActionsInfo getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actions }
     *     
     */
    public void setActions(ActionsInfo value) {
        this.actions = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link Params }
     *     
     */
    public ParamsInfo getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link Params }
     *     
     */
    public void setParams(ParamsInfo value) {
        this.params = value;
    }

    /**
     * Gets the value of the viewId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewId() {
        return viewId;
    }

    /**
     * Sets the value of the viewId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewId(String value) {
        this.viewId = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItems(String value) {
        this.items = value;
    }

    /**
     * Gets the value of the var property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVar() {
        return var;
    }

    /**
     * Sets the value of the var property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVar(String value) {
        this.var = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageSize(String value) {
        this.pageSize = value;
    }

}
