//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 10:51:57 AM MST 
//


package com.imseam.chatpage.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.imseam.chatpage.config.temp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.imseam.chatpage.config.temp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChatPagesInfo.GlobalParsers }
     * 
     */
    public ChatPagesInfo.GlobalParsersInfo createChatPagesGlobalParsers() {
        return new ChatPagesInfo.GlobalParsersInfo();
    }

    /**
     * Create an instance of {@link StringParserInfo }
     * 
     */
    public StringParserInfo createStringParser() {
        return new StringParserInfo();
    }

    /**
     * Create an instance of {@link JavaParserInfo }
     * 
     */
    public JavaParserInfo createJavaParser() {
        return new JavaParserInfo();
    }

    /**
     * Create an instance of {@link ParsersInfo }
     * 
     */
    public ParsersInfo createParsers() {
        return new ParsersInfo();
    }

    /**
     * Create an instance of {@link GroupedParserInfo }
     * 
     */
    public GroupedParserInfo createGroupedParser() {
        return new GroupedParserInfo();
    }

    /**
     * Create an instance of {@link ParserRefInfo }
     * 
     */
    public ParserRefInfo createParserRef() {
        return new ParserRefInfo();
    }

    /**
     * Create an instance of {@link RegexpParserInfo }
     * 
     */
    public RegexpParserInfo createRegexpParser() {
        return new RegexpParserInfo();
    }


    /**
     * Create an instance of {@link CommandFilterInfo }
     * 
     */
    public CommandFilterInfo createCommandFilter() {
        return new CommandFilterInfo();
    }

    /**
     * Create an instance of {@link ChatPagesInfo }
     * 
     */
    public ChatPagesInfo createChatPages() {
        return new ChatPagesInfo();
    }

    /**
     * Create an instance of {@link ActionsInfo }
     * 
     */
    public ActionsInfo createActions() {
        return new ActionsInfo();
    }

    /**
     * Create an instance of {@link CommandFilterMappingInfo }
     * 
     */
    public CommandFilterMappingInfo createCommandFilterMapping() {
        return new CommandFilterMappingInfo();
    }

    /**
     * Create an instance of {@link ParamsInfo }
     * 
     */
    public ParamsInfo createParams() {
        return new ParamsInfo();
    }

    /**
     * Create an instance of {@link ResponseInfo.Include }
     * 
     */
    public ResponseInfo.IncludeInfo createResponseInclude() {
        return new ResponseInfo.IncludeInfo();
    }

    /**
     * Create an instance of {@link ParamInfo }
     * 
     */
    public ParamInfo createParam() {
        return new ParamInfo();
    }

    /**
     * Create an instance of {@link ResponseInfo }
     * 
     */
    public ResponseInfo createResponse() {
        return new ResponseInfo();
    }

    /**
     * Create an instance of {@link ParserInfo }
     * 
     */
    public ParserInfo createParser() {
        return new ParserInfo();
    }

    /**
     * Create an instance of {@link ChatPageInfo }
     * 
     */
    public ChatPageInfo createChatPage() {
        return new ChatPageInfo();
    }

    /**
     * Create an instance of {@link ActionInfo }
     * 
     */
    public ActionInfo createAction() {
        return new ActionInfo();
    }

    /**
     * Create an instance of {@link RegexpParserInfo.RegexpParseresultInfo }
     * 
     */
    public RegexpParserInfo.RegexpParseresultInfo createRegexpParserRegexpParseresult() {
        return new RegexpParserInfo.RegexpParseresultInfo();
    }
    
    public ForeachInfo createForeach() {
        return new ForeachInfo();
    }
    
    public TextInfo createText() {
        return new TextInfo();
    }

    public MenuPageInfo createMenuPage() {
        return new MenuPageInfo();
    }

}
