//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.18 at 10:51:57 AM MST 
//


package com.imseam.chatpage.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for regexp-parser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="regexp-parser">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.imseam.com/}parser">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="regexp-parseresult">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="group-number" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="parameter-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="pattern" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="negative" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "regexp-parser", propOrder = {
    "regexpParseresult"
})
public class RegexpParserInfo
    extends ParserInfo
{

    @XmlElement(name = "regexp-parseresult")
    protected List<RegexpParserInfo.RegexpParseresultInfo> regexpParseresult;
    @XmlAttribute(required = true)
    protected String pattern;
    @XmlAttribute
    protected Boolean negative = false;

    /**
     * Gets the value of the regexpParseresult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regexpParseresult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegexpParseresult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegexpParserInfo.RegexpParseresultInfo }
     * 
     * 
     */
    public List<RegexpParserInfo.RegexpParseresultInfo> getRegexpParseresult() {
        if (regexpParseresult == null) {
            regexpParseresult = new ArrayList<RegexpParserInfo.RegexpParseresultInfo>();
        }
        return this.regexpParseresult;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the negative property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNegative() {
        return negative;
    }

    /**
     * Sets the value of the negative property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNegative(Boolean value) {
        this.negative = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="group-number" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="parameter-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RegexpParseresultInfo {

        @XmlAttribute(name = "group-number", required = true)
        protected byte groupNumber;
        @XmlAttribute(name = "parameter-name", required = true)
        protected String parameterName;

        /**
         * Gets the value of the groupNumber property.
         * 
         */
        public byte getGroupNumber() {
            return groupNumber;
        }

        /**
         * Sets the value of the groupNumber property.
         * 
         */
        public void setGroupNumber(byte value) {
            this.groupNumber = value;
        }

        /**
         * Gets the value of the parameterName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParameterName() {
            return parameterName;
        }

        /**
         * Sets the value of the parameterName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParameterName(String value) {
            this.parameterName = value;
        }

    }

}
