//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.29 at 11:59:49 PM MDT 
//


package com.imseam.chatpage.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="include" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="view-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="text" type="{http://www.imseam.com/}text" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="foreach" type="{http://www.imseam.com/}foreach" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response", propOrder = {
    "includeOrTextOrForeach"
})
public class ResponseInfo {

    @XmlElements({
        @XmlElement(name = "foreach", type = ForeachInfo.class),
        @XmlElement(name = "text", type = TextInfo.class),
        @XmlElement(name = "include", type = ResponseInfo.IncludeInfo.class)
    })
    protected List<Object> includeOrTextOrForeach;

    /**
     * Gets the value of the includeOrTextOrForeach property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includeOrTextOrForeach property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludeOrTextOrForeach().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ForeachInfo }
     * {@link TextInfo }
     * {@link Response.Include }
     * 
     * 
     */
    public List<Object> getIncludeOrTextOrForeach() {
        if (includeOrTextOrForeach == null) {
            includeOrTextOrForeach = new ArrayList<Object>();
        }
        return this.includeOrTextOrForeach;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="view-id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncludeInfo {

        @XmlAttribute(name = "view-id")
        protected String viewId;

        /**
         * Gets the value of the viewId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getViewId() {
            return viewId;
        }

        /**
         * Sets the value of the viewId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setViewId(String value) {
            this.viewId = value;
        }

    }

}
